version: '3.8'

services:
  nextjs-app:
    container_name: zein-edtech-admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    restart: always
    command: npm run dev
