version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: zein-edtech-admin
    container_name: zein-edtech-admin
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add other environment variables your app needs
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
